package cn.iocoder.yudao.module.quant.service;

import cn.iocoder.yudao.framework.common.util.json.JsonUtils;
import cn.iocoder.yudao.module.quant.api.backtest.*;
import cn.iocoder.yudao.module.quant.dal.*;
import cn.iocoder.yudao.module.quant.engine.*;
import cn.iocoder.yudao.module.quant.framework.QuantProperties;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.transaction.PlatformTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;
import java.math.BigDecimal;
import java.security.SecureRandom;
import java.util.*;

@Service
public class LiveOrderService {
    private final LiveControlRepository controls;private final LiveOrderRepository orders;private final LiveTradingClient client;private final QuantProperties properties;private final LiveControlService controlService;private final TransactionTemplate transactions;
    public LiveOrderService(LiveControlRepository controls,LiveOrderRepository orders,LiveTradingClient client,QuantProperties properties,LiveControlService controlService,PlatformTransactionManager transactionManager){this.controls=controls;this.orders=orders;this.client=client;this.properties=properties;this.controlService=controlService;this.transactions=new TransactionTemplate(transactionManager);}

    @Transactional public Map<String,Object> issue(long tenant,long owner,String policyId,LiveOrderTokenRequest request){
        if(!"CONFIRM_LIVE_ORDER".equals(request.confirmation()))throw new IllegalArgumentException("真实订单确认语不匹配");
        requireLiveReady(tenant,owner,policyId);var decision=controls.decision(tenant,owner,request.clientOrderId());
        if(decision==null||!policyId.equals(decision.get("policyId"))||!"ALLOWED_OFFLINE".equals(decision.get("decision"))||Boolean.TRUE.equals(decision.get("executed")))throw new IllegalArgumentException("订单决策不存在、未通过或已执行");
        if(orders.byClient(tenant,owner,request.clientOrderId())!=null)throw new IllegalArgumentException("订单已创建");
        orders.revokeTokens(policyId);byte[] bytes=new byte[32];new SecureRandom().nextBytes(bytes);String raw=Base64.getUrlEncoder().withoutPadding().encodeToString(bytes);String hash=DatasetRegistry.hash(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8));String id=UUID.randomUUID().toString();long expires=System.currentTimeMillis()+properties.getLiveOrderTokenTtlSeconds()*1000L;
        orders.issueToken(id,policyId,String.valueOf(decision.get("id")),tenant,owner,hash,expires);controls.audit(policyId,tenant,owner,owner,"LIVE_ORDER_TOKEN_ISSUED","ARMED_OFFLINE","ARMED_OFFLINE",request.clientOrderId()+" / "+request.comment().trim());return Map.of("token",raw,"expiresAt",expires,"clientOrderId",request.clientOrderId());
    }

    public Map<String,Object> execute(long tenant,long owner,String policyId,LiveOrderExecuteRequest request){
        requireLiveReady(tenant,owner,policyId);String hash=DatasetRegistry.hash(request.token().getBytes(java.nio.charset.StandardCharsets.UTF_8));var tokenView=orders.token(tenant,owner,policyId,hash);if(tokenView==null)throw new IllegalArgumentException("真实订单令牌无效、过期或已使用");var decisionView=decisionById(tenant,owner,String.valueOf(tokenView.get("decisionId")));validateExchangeRisk(policyId,decisionView);Reservation reservation=transactions.execute(status->{var token=orders.token(tenant,owner,policyId,hash);long now=System.currentTimeMillis();if(token==null||!orders.consume(String.valueOf(token.get("id")),now))throw new IllegalArgumentException("真实订单令牌无效、过期或已使用");var decision=decisionById(tenant,owner,String.valueOf(token.get("decisionId")));String clientId=String.valueOf(decision.get("clientOrderId"));var existing=orders.byClient(tenant,owner,clientId);if(existing!=null)return new Reservation(existing,null,null,null,null,null);BigDecimal price=decimal(decision,"price"),amount=decimal(decision,"amount"),notional=decimal(decision,"notional");String id=UUID.randomUUID().toString();orders.createSubmitting(id,policyId,String.valueOf(decision.get("id")),tenant,owner,clientId,properties.getLivePair().replace('/','-'),String.valueOf(decision.get("side")),String.valueOf(decision.get("orderType")),price,amount,notional,now+properties.getLiveOrderCancelTimeoutSeconds()*1000L);return new Reservation(null,id,clientId,String.valueOf(decision.get("side")),price,amount);});
        if(reservation.existing()!=null)return reservation.existing();String id=reservation.id(),clientId=reservation.clientId();BigDecimal price=reservation.price(),amount=reservation.amount();
        try{var response=parse(client.placeSpotLimitOrder(clientId,reservation.side(),plain(price),plain(amount)));var item=first(response);String code=text(response,"code"),sCode=text(item,"sCode");if(!"0".equals(code)||!"0".equals(sCode)){String message=text(item,"sMsg");orders.failed(id,sCode,message);throw new IllegalStateException("OKX 下单拒绝: "+sCode+" "+message);}orders.accepted(id,text(item,"ordId"),sCode,text(item,"sMsg"));controls.audit(policyId,tenant,owner,owner,"LIVE_ORDER_SUBMITTED","ARMED_OFFLINE","ARMED_OFFLINE",clientId+" / "+text(item,"ordId"));return orders.get(tenant,owner,id);}catch(RuntimeException e){var current=orders.get(tenant,owner,id);if(current!=null&&"SUBMITTING".equals(current.get("status")))orders.uncertain(id,safe(e.getMessage()));throw e;}
    }

    public Map<String,Object> refresh(long tenant,long owner,String orderId){var order=owned(tenant,owner,orderId);return refreshOrder(tenant,owner,order);}
    public Map<String,Object> cancel(long tenant,long owner,String orderId){var order=owned(tenant,owner,orderId);cancelOrder(tenant,owner,order,"MANUAL_CANCEL");return refreshOrder(tenant,owner,orders.get(tenant,owner,orderId));}
    public List<Map<String,Object>> list(long tenant,long owner,String policyId){if(controls.get(tenant,owner,policyId)==null)throw new IllegalArgumentException("实盘安全策略不存在");return orders.list(tenant,owner,policyId);}
    public void reconcilePolicy(long tenant,long owner,String policyId){for(var order:orders.reconcilable(policyId)){if(((Number)order.get("tenantId")).longValue()==tenant&&((Number)order.get("ownerId")).longValue()==owner)refreshOrder(tenant,owner,order);}}
    public int openCount(String policyId){return orders.openCount(policyId);}
    public BigDecimal dailyNotional(String policyId,long since){return orders.dailyNotional(policyId,since);}
    public String emergencyStop(long tenant,long owner,String policyId,LiveControlStopRequest request){var open=orders.open(policyId);for(var order:open){if(((Number)order.get("tenantId")).longValue()==tenant&&((Number)order.get("ownerId")).longValue()==owner)try{cancelOrder(tenant,owner,order,"EMERGENCY_STOP");}catch(RuntimeException ignored){}}return controlService.emergencyStop(tenant,owner,policyId,request);}

    @Scheduled(fixedDelay=10000) public void cancelExpired(){if(!properties.isLiveExecutionEnabled()||!client.configured())return;for(var row:orders.expired(System.currentTimeMillis()))try{cancelOrder(((Number)row.get("tenantId")).longValue(),((Number)row.get("ownerId")).longValue(),row,"AUTO_TIMEOUT");}catch(RuntimeException ignored){}}

    private void requireLiveReady(long tenant,long owner,String policyId){var policy=controls.get(tenant,owner,policyId);if(policy==null)throw new IllegalArgumentException("实盘安全策略不存在");if(!"ARMED_OFFLINE".equals(policy.get("status")))throw new IllegalArgumentException("实盘策略未启用");if(!properties.isLiveExecutionEnabled())throw new IllegalArgumentException("真实执行总开关关闭");if(!client.configured())throw new IllegalArgumentException("OKX 凭据未配置");}
    private void validateExchangeRisk(String policyId,Map<String,Object> decision){BigDecimal notional=decimal(decision,"notional"),amount=decimal(decision,"amount");var pending=parse(client.pendingOrders());if(!"0".equals(text(pending,"code")))throw new IllegalArgumentException("无法核对交易所挂单");Object pendingData=pending.get("data");int open=pendingData instanceof List<?> list?list.size():Integer.MAX_VALUE;if(open>=properties.getLiveMaxOpenOrders())throw new IllegalArgumentException("交易所挂单数已达到上限");var balance=parse(client.accountBalance());if(!"0".equals(text(balance,"code")))throw new IllegalArgumentException("无法核对交易所仓位");BigDecimal exposure=BigDecimal.ZERO,availableBtc=BigDecimal.ZERO;Object data=balance.get("data");if(!(data instanceof List<?> accounts)||accounts.isEmpty()||!(accounts.getFirst() instanceof Map<?,?> account))throw new IllegalArgumentException("交易所仓位响应不完整");Object details=account.get("details");if(!(details instanceof List<?> currencies))throw new IllegalArgumentException("交易所仓位明细缺失");for(Object value:currencies)if(value instanceof Map<?,?> currency&&"BTC".equals(String.valueOf(currency.get("ccy")))){String eqUsd=String.valueOf(currency.get("eqUsd")),avail=String.valueOf(currency.get("availBal"));if(!eqUsd.isBlank()&&!"null".equals(eqUsd))exposure=new BigDecimal(eqUsd);if(!avail.isBlank()&&!"null".equals(avail))availableBtc=new BigDecimal(avail);}if("BUY".equals(decision.get("side"))&&exposure.add(notional).compareTo(properties.getLiveMaxTotalExposure())>0)throw new IllegalArgumentException("交易所实际仓位将超过上限");if("SELL".equals(decision.get("side"))&&availableBtc.compareTo(amount)<0)throw new IllegalArgumentException("可用 BTC 不足以卖出");long dayStart=java.time.LocalDate.now(java.time.ZoneOffset.UTC).atStartOfDay(java.time.ZoneOffset.UTC).toInstant().toEpochMilli();if(orders.dailyNotional(policyId,dayStart).add(notional).compareTo(properties.getLiveMaxDailyNotional())>0)throw new IllegalArgumentException("当日真实订单金额将超过上限");}
    private Map<String,Object> owned(long tenant,long owner,String id){var order=orders.get(tenant,owner,id);if(order==null)throw new IllegalArgumentException("真实订单不存在");return order;}
    private Map<String,Object> decisionById(long tenant,long owner,String id){var decision=controls.decisionById(tenant,owner,id);if(decision==null)throw new IllegalArgumentException("订单决策不存在");return decision;}
    private Map<String,Object> refreshOrder(long tenant,long owner,Map<String,Object> order){String status=String.valueOf(order.get("status"));if(!List.of("LIVE","PARTIALLY_FILLED","CANCEL_REQUESTED","SUBMIT_UNKNOWN").contains(status))return order;var response=parse(client.getOrder(String.valueOf(order.get("clientOrderId"))));var item=first(response);requireOk(response,item,"查询订单");String mapped=mapState(text(item,"state"));orders.update(String.valueOf(order.get("id")),mapped,number(item,"accFillSz"),nullableNumber(item,"avgPx"),text(item,"sCode"),text(item,"sMsg"));return orders.get(tenant,owner,String.valueOf(order.get("id")));}
    private void cancelOrder(long tenant,long owner,Map<String,Object> order,String reason){String status=String.valueOf(order.get("status"));if(!List.of("SUBMITTING","LIVE","PARTIALLY_FILLED").contains(status))return;var response=parse(client.cancelOrder(String.valueOf(order.get("clientOrderId"))));var item=first(response);requireOk(response,item,"撤销订单");orders.update(String.valueOf(order.get("id")),"CANCEL_REQUESTED",decimal(order,"filledAmount"),nullableDecimal(order,"averagePrice"),text(item,"sCode"),reason);controls.audit(String.valueOf(order.get("policyId")),tenant,owner,owner,reason,status,"CANCEL_REQUESTED",String.valueOf(order.get("clientOrderId")));}
    @SuppressWarnings("unchecked") private static Map<String,Object> parse(String json){return JsonUtils.parseObject(json,Map.class);}
    @SuppressWarnings("unchecked") private static Map<String,Object> first(Map<String,Object> response){Object data=response.get("data");if(!(data instanceof List<?> list)||list.isEmpty()||!(list.getFirst() instanceof Map<?,?>))throw new IllegalStateException("OKX 响应缺少订单数据");return (Map<String,Object>)list.getFirst();}
    private static void requireOk(Map<String,Object> response,Map<String,Object> item,String action){if(!"0".equals(text(response,"code"))||(!text(item,"sCode").isBlank()&&!"0".equals(text(item,"sCode"))))throw new IllegalStateException("OKX "+action+"失败: "+text(response,"code")+"/"+text(item,"sCode"));}
    private static String mapState(String state){return switch(state){case "live"->"LIVE";case "partially_filled"->"PARTIALLY_FILLED";case "filled"->"FILLED";case "canceled"->"CANCELED";default->"UNKNOWN";};}
    private static String text(Map<String,Object> map,String key){Object value=map.get(key);return value==null?"":String.valueOf(value);}
    private static BigDecimal number(Map<String,Object> map,String key){String value=text(map,key);return value.isBlank()?BigDecimal.ZERO:new BigDecimal(value);}
    private static BigDecimal nullableNumber(Map<String,Object> map,String key){String value=text(map,key);return value.isBlank()?null:new BigDecimal(value);}
    private static BigDecimal decimal(Map<String,Object> map,String key){return new BigDecimal(String.valueOf(map.get(key)));}
    private static BigDecimal nullableDecimal(Map<String,Object> map,String key){Object value=map.get(key);return value==null?null:new BigDecimal(String.valueOf(value));}
    private static String plain(BigDecimal value){return value.stripTrailingZeros().toPlainString();}
    private static String safe(String value){if(value==null)return "请求失败";return value.length()>450?value.substring(0,450):value;}
    private record Reservation(Map<String,Object> existing,String id,String clientId,String side,BigDecimal price,BigDecimal amount){}
}
