package cn.iocoder.yudao.module.quant.service;

import cn.iocoder.yudao.framework.common.util.json.JsonUtils;
import cn.iocoder.yudao.module.quant.dal.*;
import cn.iocoder.yudao.module.quant.engine.DatasetRegistry;
import cn.iocoder.yudao.module.quant.framework.QuantProperties;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

@Service public class PaperDryRunPreviewService {
 private final PaperExecutionRepository executions; private final PaperSessionRepository sessionRepo; private final PaperSessionService sessions; private final BacktestRepository backtests; private final QuantProperties properties;
 public PaperDryRunPreviewService(PaperExecutionRepository executions,PaperSessionRepository sessionRepo,PaperSessionService sessions,BacktestRepository backtests,QuantProperties properties){this.executions=executions;this.sessionRepo=sessionRepo;this.sessions=sessions;this.backtests=backtests;this.properties=properties;}
 @Transactional public String create(long tenant,long owner,String executionId)throws Exception{
  var task=executions.get(tenant,owner,executionId);if(task==null)throw new IllegalArgumentException("模拟盘执行任务不存在");if(!"WAITING_ENABLE".equals(task.get("status")))throw new IllegalArgumentException("仅待启用任务可生成命令预览");if(properties.isPaperExecutionEnabled())throw new IllegalArgumentException("预览阶段要求执行总开关关闭");var existing=executions.preview(executionId);if(existing!=null)return (String)existing.get("id");
  var session=sessions.approvedCurrent(tenant,owner,(String)task.get("session_id"));var readiness=sessionRepo.readiness((String)task.get("readiness_snapshot_id"));if(readiness==null||!truth(readiness.get("ready"))||!Objects.equals(task.get("readiness_hash"),readiness.get("manifestHash")))throw new IllegalArgumentException("任务绑定的就绪快照无效");
  var parameter=backtests.findParameterSet(tenant,owner,(String)session.get("parameter_set_id"));var version=backtests.findVersion(tenant,owner,(String)session.get("strategy_version_id"));if(parameter==null||version==null)throw new IllegalArgumentException("策略版本或参数集不存在");String source=(String)version.get("sourceCode"),sourceHash=(String)version.get("sourceHash");if(!sourceHash.equals(DatasetRegistry.hash(source.getBytes(StandardCharsets.UTF_8))))throw new IllegalArgumentException("策略源码摘要不一致");var values=JsonUtils.getObjectMapper().readTree((String)parameter.get("parametersJson"));
  Map<String,Object> config=new TreeMap<>();config.put("dry_run",true);config.put("dry_run_wallet",values.path("startingBalance").asDouble());config.put("stake_currency","USDT");config.put("stake_amount",values.path("stakeAmount").asDouble());config.put("max_open_trades",1);config.put("trading_mode","spot");config.put("timeframe","1h");config.put("initial_state","running");config.put("db_url","sqlite:////freqtrade/user_data/tradesv3.dryrun.sqlite");config.put("entry_pricing",Map.of("price_side","same","use_order_book",true,"order_book_top",1,"price_last_balance",0.0,"check_depth_of_market",Map.of("enabled",false,"bids_to_ask_delta",1)));config.put("exit_pricing",Map.of("price_side","same","use_order_book",true,"order_book_top",1));config.put("pairlists",List.of(Map.of("method","StaticPairList")));Map<String,Object> exchange=new TreeMap<>();exchange.put("name","okx");exchange.put("pair_whitelist",List.of("BTC/USDT"));exchange.put("pair_blacklist",List.of());if(properties.getExchangeProxy()!=null&&!properties.getExchangeProxy().isBlank()){exchange.put("ccxt_config",Map.of("httpsProxy",properties.getExchangeProxy()));exchange.put("ccxt_async_config",Map.of("httpsProxy",properties.getExchangeProxy()));}config.put("exchange",exchange);String configJson=JsonUtils.toJsonString(config);if(configJson.toLowerCase().matches(".*\"(key|secret|password|token)\".*"))throw new IllegalArgumentException("配置包含禁止的凭据字段");
  Path root=Path.of(properties.getWorkspace()).toAbsolutePath().normalize(),paperRoot=root.resolve("paper").normalize(),work=paperRoot.resolve(executionId).normalize();if(!work.startsWith(paperRoot))throw new IllegalArgumentException("工作目录越界");Files.createDirectories(paperRoot);if(Files.exists(work))throw new IllegalArgumentException("执行工作目录已存在，请人工核查");Path temp=paperRoot.resolve(executionId+".preparing").normalize();Files.createDirectories(temp.resolve("strategies"));Files.writeString(temp.resolve("config.json"),configJson,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);Files.writeString(temp.resolve("strategies").resolve("QuantEmaBaseline.py"),source,StandardCharsets.UTF_8,StandardOpenOption.CREATE_NEW);try{Files.move(temp,work,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException ignored){Files.move(temp,work);}
  List<String> command=List.of(properties.getDockerExecutable(),"run","--name",(String)task.get("container_name"),"--rm","--read-only","--network=bridge","--cap-drop=ALL","--security-opt=no-new-privileges","--cpus=1","--memory=1g","--pids-limit=128","--tmpfs","/tmp:rw,noexec,nosuid,size=64m","--mount","type=bind,src="+work+",dst=/freqtrade/user_data",properties.getImage(),"trade","--config","/freqtrade/user_data/config.json","--strategy-path","/freqtrade/user_data/strategies","--strategy","QuantEmaBaseline");
  Map<String,Object> preview=new TreeMap<>();preview.put("schema","quant-paper-command-preview/v1");preview.put("executionId",executionId);preview.put("readinessHash",task.get("readiness_hash"));preview.put("configHash",DatasetRegistry.hash(configJson.getBytes(StandardCharsets.UTF_8)));preview.put("strategyHash",sourceHash);preview.put("containerName",task.get("container_name"));preview.put("command",command);preview.put("network","docker-default-bridge");preview.put("portsPublished",false);preview.put("credentialsIncluded",false);preview.put("executed",false);String json=JsonUtils.toJsonString(preview),hash=DatasetRegistry.hash(json.getBytes(StandardCharsets.UTF_8)),id=UUID.randomUUID().toString();executions.preview(id,executionId,json,hash,work.toString());executions.audit(executionId,owner,"PREVIEW_CREATED","WAITING_ENABLE","WAITING_ENABLE","安全命令预览已生成；未执行 Docker");return id;
 }
 public Map<String,Object> get(long tenant,long owner,String executionId){if(executions.get(tenant,owner,executionId)==null)throw new IllegalArgumentException("模拟盘执行任务不存在");var preview=executions.preview(executionId);if(preview==null)throw new IllegalArgumentException("命令预览尚未生成");return preview;}
 private static boolean truth(Object value){return Boolean.TRUE.equals(value)||(value instanceof Number n&&n.intValue()==1);}
}
