CREATE TABLE IF NOT EXISTS quant_paper_observation_snapshot (
  id VARCHAR(36) PRIMARY KEY,
  execution_id VARCHAR(36) NOT NULL,
  tenant_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  execution_status VARCHAR(32) NOT NULL,
  heartbeat_age_seconds BIGINT,
  last_heartbeat_at BIGINT,
  last_market_data_at BIGINT,
  network_error_count INT NOT NULL,
  fatal_error_count INT NOT NULL,
  soak_seconds BIGINT NOT NULL,
  soak_passed BIT NOT NULL,
  database_available BIT NOT NULL,
  estimated_available_balance DECIMAL(24,8) NOT NULL,
  open_positions INT NOT NULL,
  closed_trades INT NOT NULL,
  open_orders INT NOT NULL,
  total_orders INT NOT NULL,
  realized_profit DECIMAL(24,8) NOT NULL,
  invested_stake DECIMAL(24,8) NOT NULL,
  evidence_hash VARCHAR(64) NOT NULL,
  observed_at BIGINT NOT NULL,
  KEY idx_quant_paper_observation_execution (execution_id, observed_at),
  KEY idx_quant_paper_observation_owner (tenant_id, owner_id, observed_at),
  CONSTRAINT fk_quant_paper_observation_execution FOREIGN KEY (execution_id) REFERENCES quant_paper_execution(id)
);

CREATE TABLE IF NOT EXISTS quant_paper_alert (
  id VARCHAR(36) PRIMARY KEY,
  execution_id VARCHAR(36) NOT NULL,
  tenant_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  alert_type VARCHAR(32) NOT NULL,
  severity VARCHAR(16) NOT NULL,
  status VARCHAR(16) NOT NULL,
  evidence VARCHAR(500) NOT NULL,
  first_observed_at BIGINT NOT NULL,
  last_observed_at BIGINT NOT NULL,
  resolved_at BIGINT,
  UNIQUE KEY uk_quant_paper_alert_type (execution_id, alert_type),
  KEY idx_quant_paper_alert_owner (tenant_id, owner_id, status, last_observed_at),
  CONSTRAINT fk_quant_paper_alert_execution FOREIGN KEY (execution_id) REFERENCES quant_paper_execution(id)
);
