CREATE TABLE IF NOT EXISTS quant_live_order_token (
  id VARCHAR(36) PRIMARY KEY,
  policy_id VARCHAR(36) NOT NULL,
  decision_id VARCHAR(36) NOT NULL,
  tenant_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  token_hash VARCHAR(64) NOT NULL,
  status VARCHAR(16) NOT NULL,
  expires_at BIGINT NOT NULL,
  consumed_at BIGINT,
  created_at BIGINT NOT NULL,
  KEY idx_quant_live_token_decision (decision_id, created_at),
  KEY idx_quant_live_token_policy (policy_id, created_at),
  CONSTRAINT fk_quant_live_token_policy FOREIGN KEY (policy_id) REFERENCES quant_live_control_policy(id),
  CONSTRAINT fk_quant_live_token_decision FOREIGN KEY (decision_id) REFERENCES quant_live_order_decision(id)
);

CREATE TABLE IF NOT EXISTS quant_live_exchange_order (
  id VARCHAR(36) PRIMARY KEY,
  policy_id VARCHAR(36) NOT NULL,
  decision_id VARCHAR(36) NOT NULL,
  tenant_id BIGINT NOT NULL,
  owner_id BIGINT NOT NULL,
  client_order_id VARCHAR(64) NOT NULL,
  exchange_order_id VARCHAR(64),
  instrument_id VARCHAR(32) NOT NULL,
  side VARCHAR(8) NOT NULL,
  order_type VARCHAR(16) NOT NULL,
  price DECIMAL(20,8) NOT NULL,
  amount DECIMAL(20,8) NOT NULL,
  notional DECIMAL(20,8) NOT NULL,
  status VARCHAR(24) NOT NULL,
  filled_amount DECIMAL(20,8) NOT NULL DEFAULT 0,
  average_price DECIMAL(20,8),
  raw_code VARCHAR(32),
  raw_message VARCHAR(500),
  submitted_at BIGINT,
  updated_at BIGINT NOT NULL,
  cancel_deadline_at BIGINT NOT NULL,
  UNIQUE KEY uk_quant_live_exchange_client (tenant_id, owner_id, client_order_id),
  KEY idx_quant_live_exchange_policy (policy_id, updated_at),
  KEY idx_quant_live_exchange_timeout (status, cancel_deadline_at),
  CONSTRAINT fk_quant_live_exchange_policy FOREIGN KEY (policy_id) REFERENCES quant_live_control_policy(id),
  CONSTRAINT fk_quant_live_exchange_decision FOREIGN KEY (decision_id) REFERENCES quant_live_order_decision(id)
);
