package cn.iocoder.yudao.module.quant.dal;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.*;

@Repository
public class LiveOrderRepository {
    private final JdbcTemplate jdbc;
    public LiveOrderRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

    public void revokeTokens(String policy){jdbc.update("UPDATE quant_live_order_token SET status='REVOKED' WHERE policy_id=? AND status='ISSUED'",policy);}
    public void issueToken(String id,String policy,String decision,long tenant,long owner,String hash,long expires){long now=System.currentTimeMillis();jdbc.update("INSERT INTO quant_live_order_token(id,policy_id,decision_id,tenant_id,owner_id,token_hash,status,expires_at,created_at) VALUES(?,?,?,?,?,?,'ISSUED',?,?)",id,policy,decision,tenant,owner,hash,expires,now);}
    public Map<String,Object> token(long tenant,long owner,String policy,String hash){return one("SELECT id,decision_id AS decisionId,status,expires_at AS expiresAt FROM quant_live_order_token WHERE tenant_id=? AND owner_id=? AND policy_id=? AND token_hash=?",tenant,owner,policy,hash);}
    public boolean consume(String id,long now){return jdbc.update("UPDATE quant_live_order_token SET status='CONSUMED',consumed_at=? WHERE id=? AND status='ISSUED' AND expires_at>=?",now,id,now)==1;}
    public void createSubmitting(String id,String policy,String decision,long tenant,long owner,String client,String instrument,String side,String type,BigDecimal price,BigDecimal amount,BigDecimal notional,long deadline){jdbc.update("INSERT INTO quant_live_exchange_order(id,policy_id,decision_id,tenant_id,owner_id,client_order_id,instrument_id,side,order_type,price,amount,notional,status,updated_at,cancel_deadline_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'SUBMITTING',?,?)",id,policy,decision,tenant,owner,client,instrument,side,type,price,amount,notional,System.currentTimeMillis(),deadline);}
    public void accepted(String id,String exchangeId,String code,String message){long now=System.currentTimeMillis();jdbc.update("UPDATE quant_live_exchange_order SET exchange_order_id=?,status='LIVE',raw_code=?,raw_message=?,submitted_at=?,updated_at=? WHERE id=?",exchangeId,code,message,now,now,id);jdbc.update("UPDATE quant_live_order_decision SET executed=1 WHERE id=(SELECT decision_id FROM quant_live_exchange_order WHERE id=?)",id);}
    public void failed(String id,String code,String message){jdbc.update("UPDATE quant_live_exchange_order SET status='FAILED',raw_code=?,raw_message=?,updated_at=? WHERE id=?",code,message,System.currentTimeMillis(),id);}
    public void uncertain(String id,String message){jdbc.update("UPDATE quant_live_exchange_order SET status='SUBMIT_UNKNOWN',raw_code='CLIENT_ERROR',raw_message=?,updated_at=? WHERE id=?",message,System.currentTimeMillis(),id);}
    public void update(String id,String status,BigDecimal filled,BigDecimal average,String code,String message){jdbc.update("UPDATE quant_live_exchange_order SET status=?,filled_amount=?,average_price=?,raw_code=?,raw_message=?,updated_at=? WHERE id=?",status,filled,average,code,message,System.currentTimeMillis(),id);}
    public Map<String,Object> get(long tenant,long owner,String id){return one("SELECT id,policy_id AS policyId,decision_id AS decisionId,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,order_type AS orderType,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,raw_code AS responseCode,raw_message AS responseMessage,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND id=?",tenant,owner,id);}
    public Map<String,Object> byClient(long tenant,long owner,String client){return one("SELECT id,policy_id AS policyId,decision_id AS decisionId,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,order_type AS orderType,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,raw_code AS responseCode,raw_message AS responseMessage,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND client_order_id=?",tenant,owner,client);}
    public List<Map<String,Object>> list(long tenant,long owner,String policy){return jdbc.queryForList("SELECT id,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND policy_id=? ORDER BY updated_at DESC LIMIT 100",tenant,owner,policy);}
    public List<Map<String,Object>> open(String policy){return jdbc.queryForList("SELECT id,policy_id AS policyId,tenant_id AS tenantId,owner_id AS ownerId,client_order_id AS clientOrderId,status,filled_amount AS filledAmount,average_price AS averagePrice FROM quant_live_exchange_order WHERE policy_id=? AND status IN ('SUBMITTING','LIVE','PARTIALLY_FILLED')",policy);}
    public List<Map<String,Object>> expired(long now){return jdbc.queryForList("SELECT id,tenant_id AS tenantId,owner_id AS ownerId,policy_id AS policyId,client_order_id AS clientOrderId,status,filled_amount AS filledAmount,average_price AS averagePrice FROM quant_live_exchange_order WHERE status IN ('LIVE','PARTIALLY_FILLED') AND cancel_deadline_at<=?",now);}
    public BigDecimal dailyNotional(String policy,long since){BigDecimal value=jdbc.queryForObject("SELECT COALESCE(SUM(notional),0) FROM quant_live_exchange_order WHERE policy_id=? AND submitted_at>=? AND status<>'FAILED'",BigDecimal.class,policy,since);return value==null?BigDecimal.ZERO:value;}
    private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);return rows.isEmpty()?null:rows.getFirst();}
}
