package cn.iocoder.yudao.module.quant.dal;

import org.springframework.dao.DuplicateKeyException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.util.*;

@Repository
public class LiveAutomationRepository {
    private final JdbcTemplate jdbc;
    public LiveAutomationRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

    public String create(String policy,long tenant,long owner,BigDecimal notional,BigDecimal maxLoss,BigDecimal equity){String id=UUID.randomUUID().toString();long now=System.currentTimeMillis();jdbc.update("INSERT INTO quant_live_automation_session(id,policy_id,tenant_id,owner_id,strategy_name,timeframe,order_notional,max_session_loss,start_equity,high_equity,last_equity,status,last_heartbeat_at,started_at,updated_at) VALUES(?,?,?,?, 'QuantEmaBaseline','1h',?,?,?,?,?, 'RUNNING',?,?,?)",id,policy,tenant,owner,notional,maxLoss,equity,equity,equity,now,now,now);return id;}
    public Map<String,Object> active(long tenant,long owner,String policy){return one("SELECT "+fields()+" FROM quant_live_automation_session WHERE tenant_id=? AND owner_id=? AND policy_id=? AND status='RUNNING' ORDER BY started_at DESC LIMIT 1",tenant,owner,policy);}
    public List<Map<String,Object>> active(){return jdbc.queryForList("SELECT "+fields()+" FROM quant_live_automation_session WHERE status='RUNNING' ORDER BY started_at");}
    public Map<String,Object> get(long tenant,long owner,String id){return one("SELECT "+fields()+" FROM quant_live_automation_session WHERE tenant_id=? AND owner_id=? AND id=?",tenant,owner,id);}
    public List<Map<String,Object>> list(long tenant,long owner,String policy){return jdbc.queryForList("SELECT "+fields()+" FROM quant_live_automation_session WHERE tenant_id=? AND owner_id=? AND policy_id=? ORDER BY started_at DESC LIMIT 50",tenant,owner,policy);}
    public void heartbeat(String id,BigDecimal equity,long candle){long now=System.currentTimeMillis();jdbc.update("UPDATE quant_live_automation_session SET high_equity=GREATEST(high_equity,?),last_equity=?,last_heartbeat_at=?,last_candle_at=?,updated_at=? WHERE id=? AND status='RUNNING'",equity,equity,now,candle,now,id);}
    public boolean stop(String id,String status,String reason){long now=System.currentTimeMillis();return jdbc.update("UPDATE quant_live_automation_session SET status=?,stop_reason=?,stopped_at=?,updated_at=? WHERE id=? AND status='RUNNING'",status,reason,now,now,id)==1;}
    public int failInterrupted(){long now=System.currentTimeMillis();return jdbc.update("UPDATE quant_live_automation_session SET status='FAILED',stop_reason='应用重启后不自动恢复',stopped_at=?,updated_at=? WHERE status='RUNNING'",now,now);}
    public boolean insertSignal(String id,String session,String policy,long tenant,long owner,long candle,String type,BigDecimal close,BigDecimal fast,BigDecimal slow,String hash,String client){long now=System.currentTimeMillis();try{jdbc.update("INSERT INTO quant_live_strategy_signal(id,session_id,policy_id,tenant_id,owner_id,candle_at,signal_type,close_price,fast_ema,slow_ema,signal_hash,client_order_id,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'DETECTED',?,?)",id,session,policy,tenant,owner,candle,type,close,fast,slow,hash,client,now,now);return true;}catch(DuplicateKeyException ignored){return false;}}
    public void signalResult(String id,String status,String decision,String order,String message){jdbc.update("UPDATE quant_live_strategy_signal SET status=?,decision_id=?,exchange_order_id=?,message=?,updated_at=? WHERE id=?",status,decision,order,safe(message),System.currentTimeMillis(),id);}
    public List<Map<String,Object>> signals(long tenant,long owner,String session){return jdbc.queryForList("SELECT id,candle_at AS candleAt,signal_type AS signalType,close_price AS closePrice,fast_ema AS fastEma,slow_ema AS slowEma,signal_hash AS signalHash,client_order_id AS clientOrderId,decision_id AS decisionId,exchange_order_id AS exchangeOrderId,status,message,created_at AS createdAt,updated_at AS updatedAt FROM quant_live_strategy_signal WHERE tenant_id=? AND owner_id=? AND session_id=? ORDER BY candle_at DESC LIMIT 100",tenant,owner,session);}
    public List<Map<String,Object>> positionFills(String session){return jdbc.queryForList("SELECT o.side,o.filled_amount AS amount,o.average_price AS price FROM quant_live_exchange_order o WHERE EXISTS(SELECT 1 FROM quant_live_strategy_signal s WHERE s.session_id=? AND s.tenant_id=o.tenant_id AND s.owner_id=o.owner_id AND s.policy_id=o.policy_id AND (s.exchange_order_id=o.id OR s.client_order_id=o.client_order_id)) AND o.filled_amount>0 ORDER BY o.submitted_at,o.id",session);}
    public BigDecimal filledPosition(String session){BigDecimal value=jdbc.queryForObject("SELECT COALESCE(SUM(CASE s.signal_type WHEN 'BUY' THEN o.filled_amount WHEN 'SELL' THEN -o.filled_amount ELSE 0 END),0) FROM quant_live_strategy_signal s JOIN quant_live_exchange_order o ON o.id=s.exchange_order_id WHERE s.session_id=?",BigDecimal.class,session);return value==null||value.signum()<0?BigDecimal.ZERO:value;}
    public void snapshot(String session,long tenant,long owner,BigDecimal equity,BigDecimal exposure,int exchangeOpen,int platformOpen,BigDecimal loss,String status,String hash,String error){jdbc.update("INSERT INTO quant_live_reconciliation_snapshot(id,session_id,tenant_id,owner_id,total_equity,btc_exposure,exchange_open_orders,platform_open_orders,session_loss,reconciliation_status,evidence_hash,error_message,reconciled_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)",UUID.randomUUID().toString(),session,tenant,owner,equity,exposure,exchangeOpen,platformOpen,loss,status,hash,safe(error),System.currentTimeMillis());}
    public List<Map<String,Object>> snapshots(long tenant,long owner,String session){return jdbc.queryForList("SELECT id,total_equity AS totalEquity,btc_exposure AS btcExposure,exchange_open_orders AS exchangeOpenOrders,platform_open_orders AS platformOpenOrders,session_loss AS sessionLoss,reconciliation_status AS reconciliationStatus,evidence_hash AS evidenceHash,error_message AS errorMessage,reconciled_at AS reconciledAt FROM quant_live_reconciliation_snapshot WHERE tenant_id=? AND owner_id=? AND session_id=? ORDER BY reconciled_at DESC LIMIT 100",tenant,owner,session);}
    public void alert(String session,long tenant,long owner,String type,String message){long now=System.currentTimeMillis();jdbc.update("INSERT INTO quant_live_automation_alert(id,session_id,tenant_id,owner_id,alert_type,severity,status,message,first_seen_at,last_seen_at) VALUES(?,?,?,?,?,'HIGH','OPEN',?,?,?) ON DUPLICATE KEY UPDATE status='OPEN',message=VALUES(message),last_seen_at=VALUES(last_seen_at),resolved_at=NULL",UUID.randomUUID().toString(),session,tenant,owner,type,safe(message),now,now);}
    public void resolve(String session,String type){jdbc.update("UPDATE quant_live_automation_alert SET status='RESOLVED',resolved_at=?,last_seen_at=? WHERE session_id=? AND alert_type=? AND status='OPEN'",System.currentTimeMillis(),System.currentTimeMillis(),session,type);}
    public List<Map<String,Object>> alerts(long tenant,long owner,String session){return jdbc.queryForList("SELECT id,alert_type AS alertType,severity,status,message,first_seen_at AS firstSeenAt,last_seen_at AS lastSeenAt,resolved_at AS resolvedAt FROM quant_live_automation_alert WHERE tenant_id=? AND owner_id=? AND session_id=? ORDER BY last_seen_at DESC",tenant,owner,session);}
    private static String fields(){return "id,policy_id AS policyId,tenant_id AS tenantId,owner_id AS ownerId,strategy_name AS strategyName,timeframe,order_notional AS orderNotional,max_session_loss AS maxSessionLoss,start_equity AS startEquity,high_equity AS highEquity,last_equity AS lastEquity,status,last_heartbeat_at AS lastHeartbeatAt,last_candle_at AS lastCandleAt,stop_reason AS stopReason,started_at AS startedAt,stopped_at AS stoppedAt,updated_at AS updatedAt";}
    private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);return rows.isEmpty()?null:rows.getFirst();}
    private static String safe(String value){if(value==null)return null;return value.length()>500?value.substring(0,500):value;}
}
