package cn.iocoder.yudao.module.quant.dal;

import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.*;

@Repository
public class LiveOrderRepository {
    private final JdbcTemplate jdbc;
    public LiveOrderRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

    public void revokeTokens(String policy){jdbc.update("UPDATE quant_live_order_token SET status='REVOKED' WHERE policy_id=? AND status='ISSUED'",policy);}
    public void issueToken(String id,String policy,String decision,long tenant,long owner,String hash,long expires){long now=System.currentTimeMillis();jdbc.update("INSERT INTO quant_live_order_token(id,policy_id,decision_id,tenant_id,owner_id,token_hash,status,expires_at,created_at) VALUES(?,?,?,?,?,?,'ISSUED',?,?)",id,policy,decision,tenant,owner,hash,expires,now);}
    public Map<String,Object> token(long tenant,long owner,String policy,String hash){return one("SELECT id,decision_id AS decisionId,status,expires_at AS expiresAt FROM quant_live_order_token WHERE tenant_id=? AND owner_id=? AND policy_id=? AND token_hash=?",tenant,owner,policy,hash);}
    public boolean consume(String id,long now){return jdbc.update("UPDATE quant_live_order_token SET status='CONSUMED',consumed_at=? WHERE id=? AND status='ISSUED' AND expires_at>=?",now,id,now)==1;}
    public void createSubmitting(String id,String policy,String decision,long tenant,long owner,String client,String instrument,String side,String type,BigDecimal price,BigDecimal amount,BigDecimal notional,long deadline){jdbc.update("INSERT INTO quant_live_exchange_order(id,policy_id,decision_id,tenant_id,owner_id,client_order_id,instrument_id,side,order_type,price,amount,notional,status,updated_at,reserved_at,cancel_deadline_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?, 'SUBMITTING',?,?,?)",id,policy,decision,tenant,owner,client,instrument,side,type,price,amount,notional,System.currentTimeMillis(),System.currentTimeMillis(),deadline);}
    public void accepted(String id,String exchangeId,String code,String message){long now=System.currentTimeMillis();jdbc.update("UPDATE quant_live_exchange_order SET exchange_order_id=?,status='LIVE',raw_code=?,raw_message=?,submitted_at=?,updated_at=? WHERE id=?",exchangeId,code,message,now,now,id);jdbc.update("UPDATE quant_live_order_decision SET executed=1 WHERE id=(SELECT decision_id FROM quant_live_exchange_order WHERE id=?)",id);}
    public void failed(String id,String code,String message){jdbc.update("UPDATE quant_live_exchange_order SET status='FAILED',raw_code=?,raw_message=?,updated_at=? WHERE id=?",code,message,System.currentTimeMillis(),id);}
    public void uncertain(String id,String message){jdbc.update("UPDATE quant_live_exchange_order SET status='SUBMIT_UNKNOWN',raw_code='CLIENT_ERROR',raw_message=?,updated_at=? WHERE id=?",message,System.currentTimeMillis(),id);}
    public void update(String id,String status,BigDecimal filled,BigDecimal average,String code,String message){jdbc.update("UPDATE quant_live_exchange_order SET status=?,filled_amount=?,average_price=?,raw_code=?,raw_message=?,updated_at=? WHERE id=?",status,filled,average,code,message,System.currentTimeMillis(),id);}
    public void updateCosts(String id,String status,BigDecimal filled,BigDecimal average,String code,String message,BigDecimal fee,String feeCurrency,BigDecimal rebate,String rebateCurrency){
        jdbc.update("UPDATE quant_live_exchange_order SET status=?,filled_amount=?,average_price=?,raw_code=?,raw_message=?,fee_amount=?,fee_currency=?,rebate_amount=?,rebate_currency=?,updated_at=? WHERE id=?",status,filled,average,code,message,fee,feeCurrency,rebate,rebateCurrency,System.currentTimeMillis(),id);
    }
    public Map<String,Object> get(long tenant,long owner,String id){return one("SELECT id,policy_id AS policyId,decision_id AS decisionId,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,order_type AS orderType,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,raw_code AS responseCode,raw_message AS responseMessage,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND id=?",tenant,owner,id);}
    public Map<String,Object> byClient(long tenant,long owner,String client){return one("SELECT id,policy_id AS policyId,decision_id AS decisionId,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,order_type AS orderType,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,raw_code AS responseCode,raw_message AS responseMessage,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND client_order_id=?",tenant,owner,client);}
    public List<Map<String,Object>> list(long tenant,long owner,String policy){return jdbc.queryForList("SELECT id,client_order_id AS clientOrderId,exchange_order_id AS exchangeOrderId,instrument_id AS instrumentId,side,price,amount,notional,status,filled_amount AS filledAmount,average_price AS averagePrice,submitted_at AS submittedAt,updated_at AS updatedAt,cancel_deadline_at AS cancelDeadlineAt FROM quant_live_exchange_order WHERE tenant_id=? AND owner_id=? AND policy_id=? ORDER BY updated_at DESC LIMIT 100",tenant,owner,policy);}
    public List<Map<String,Object>> open(String policy){return jdbc.queryForList("SELECT id,policy_id AS policyId,tenant_id AS tenantId,owner_id AS ownerId,client_order_id AS clientOrderId,status,filled_amount AS filledAmount,average_price AS averagePrice FROM quant_live_exchange_order WHERE policy_id=? AND status IN ('SUBMITTING','LIVE','PARTIALLY_FILLED')",policy);}
    public List<Map<String,Object>> reconcilable(String policy){return jdbc.queryForList("SELECT id,policy_id AS policyId,tenant_id AS tenantId,owner_id AS ownerId,client_order_id AS clientOrderId,status,filled_amount AS filledAmount,average_price AS averagePrice FROM quant_live_exchange_order WHERE policy_id=? AND status NOT IN ('FAILED','FILLED','CANCELED')",policy);}
    public int openCount(String policy){Integer value=jdbc.queryForObject("SELECT COUNT(*) FROM quant_live_exchange_order WHERE policy_id=? AND status NOT IN ('FAILED','FILLED','CANCELED')",Integer.class,policy);return value==null?0:value;}
    public List<Map<String,Object>> expired(long now){return jdbc.queryForList("SELECT id,tenant_id AS tenantId,owner_id AS ownerId,policy_id AS policyId,client_order_id AS clientOrderId,status,filled_amount AS filledAmount,average_price AS averagePrice FROM quant_live_exchange_order WHERE status IN ('LIVE','PARTIALLY_FILLED') AND cancel_deadline_at<=?",now);}
    public BigDecimal dailyNotional(String policy,long since){BigDecimal value=jdbc.queryForObject("SELECT COALESCE(SUM(notional),0) FROM quant_live_exchange_order WHERE policy_id=? AND COALESCE(reserved_at,submitted_at,updated_at)>=? AND status<>'FAILED'",BigDecimal.class,policy,since);return value==null?BigDecimal.ZERO:value;}
    /** One configured exchange account is shared by all policies, tenants and owners. */
    public void lockAccount(){jdbc.queryForObject("SELECT id FROM quant_live_account_guard WHERE id=1 FOR UPDATE",Integer.class);}
    public List<Map<String,Object>> accountActive(){return jdbc.queryForList("SELECT client_order_id AS clientOrderId,side,price,amount,filled_amount AS filledAmount,status FROM quant_live_exchange_order WHERE status NOT IN ('FAILED','FILLED','CANCELED')");}
    public BigDecimal accountDailyNotional(long since){return jdbc.queryForObject("SELECT COALESCE(SUM(notional),0) FROM quant_live_exchange_order WHERE COALESCE(reserved_at,submitted_at,updated_at)>=? AND status<>'FAILED'",BigDecimal.class,since);}
    public boolean ownsSession(long tenant,long owner,String policy,String session){return jdbc.queryForObject("SELECT COUNT(*) FROM quant_live_automation_session WHERE tenant_id=? AND owner_id=? AND policy_id=? AND id=?",Integer.class,tenant,owner,policy,session)==1;}
    public String sessionForClient(long tenant,long owner,String policy,String client){
        var rows=jdbc.queryForList("SELECT DISTINCT session_id AS sessionId FROM quant_live_strategy_signal WHERE tenant_id=? AND owner_id=? AND policy_id=? AND client_order_id=?",tenant,owner,policy,client);
        if(rows.size()>1)throw new IllegalArgumentException("订单归属会话冲突");
        return rows.isEmpty()?null:String.valueOf(rows.getFirst().get("sessionId"));
    }
    public List<Map<String,Object>> inventoryRows(long tenant,long owner,String policy,String session){
        String scope=session==null?"NOT EXISTS (SELECT 1 FROM quant_live_strategy_signal s WHERE s.tenant_id=o.tenant_id AND s.owner_id=o.owner_id AND s.policy_id=o.policy_id AND (s.exchange_order_id=o.id OR s.client_order_id=o.client_order_id))":"EXISTS (SELECT 1 FROM quant_live_strategy_signal s WHERE s.session_id=? AND s.tenant_id=o.tenant_id AND s.owner_id=o.owner_id AND s.policy_id=o.policy_id AND (s.exchange_order_id=o.id OR s.client_order_id=o.client_order_id))";
        String sql="SELECT (SELECT COUNT(DISTINCT x.session_id) FROM quant_live_strategy_signal x WHERE x.tenant_id=o.tenant_id AND x.owner_id=o.owner_id AND x.policy_id=o.policy_id AND (x.exchange_order_id=o.id OR x.client_order_id=o.client_order_id)) AS sessionOwners,o.id,o.side,o.status,o.amount,o.filled_amount AS filledAmount,o.average_price AS averagePrice,o.fee_amount AS feeAmount,o.fee_currency AS feeCurrency,o.rebate_amount AS rebateAmount,o.rebate_currency AS rebateCurrency FROM quant_live_exchange_order o WHERE o.tenant_id=? AND o.owner_id=? AND o.policy_id=? AND "+scope;
        var rows=session==null?jdbc.queryForList(sql,tenant,owner,policy):jdbc.queryForList(sql,tenant,owner,policy,session);
        for(var row:rows)if(((Number)row.get("sessionOwners")).intValue()>1)throw new IllegalArgumentException("Inventory ownership conflict");
        return rows;
    }
    private Map<String,Object> one(String sql,Object...args){var rows=jdbc.queryForList(sql,args);return rows.isEmpty()?null:rows.getFirst();}
}
